### ISSUE TITLE
i encountered issue in 0.6 version 

### ISSUE THREAD

**Issue by wangbuu0910** [meizhong986/WhisperJAV#3] opened 2024-01-03 10:28 UTC
when i converting my audio file this message appeared on last step/process 
![Untitled](https://github.com/meizhong986/WhisperJAV/assets/155535884/e4de14e3-0f57-4dc8-be49-5193790b04e4)

**Comment by dgoryeo** [comment] 2024-01-03 12:55
Thanks for the report. Do you receive the warning always, or only if you have selected "translate with deepl"?

**Comment by Pochoxo** [comment] 2024-01-03 20:11
This is the same error I posted about yesterday and I get the error always (without using 'translate with deepl').

**Comment by foristickman** [comment] 2024-01-03 22:11
It seems to be hanging on line 48. Sometimes it downloads 1 or 2 required files while other times it just hangs. It doesn't time out either I had it hanging for over 6 hours yesterday.

**Comment by wangbuu0910** [comment] 2024-01-03 23:47
> Thanks for the report. Do you receive the warning always, or only if you have selected "translate with deepl"?

no i didnt select translate with deepl I always do what I always do when translating but this latest version i got this from yesterday.

**Comment by meizhong986** [comment] 2024-01-04 10:51
Thanks. 

It seems that the warning that you receive is not the cause of the problem, but the cuda incompatibility after google upgraded colab. 

https://github.com/googlecolab/colabtools/issues/4214

It seems that the fallback method is not working any longer in colab. I will need to find a workaround.

**Comment by wangbuu0910** [comment] 2024-01-04 12:14
> Thanks.
> 
> It seems that the warning that you receive is not the cause of the problem, but the cuda incompatibility after google upgraded colab.
> 
> [googlecolab/colabtools#4214](https://github.com/googlecolab/colabtools/issues/4214)
> 
> It seems that the fallback method is not working any longer in colab. I will need to find a workaround.

thanks sir i hope it will fix soon :-)

**Comment by wangbuu0910** [comment] 2024-01-04 12:30
![Untitled1](https://github.com/meizhong986/WhisperJAV/assets/155535884/a7fd7174-2c54-49a0-9dcf-49557a2c702c)
guys 
![Untitled11](https://github.com/meizhong986/WhisperJAV/assets/155535884/626faf24-450a-40c9-8236-29a043e6ea72)
follow this tutorial for temporary it works for me now.

**Comment by meizhong986** [comment] 2024-01-04 13:05
For now version 1.0 BETA is a quick workaround. Please check it out to see that it works in your env.  
Note: the speed is not as fast as 0.6. We have to wait for the root cause problem to be solved before going back to the 2x speed.

**Comment by dhezn1256** [comment] 2024-01-04 20:52
1.0 beta works, but is very slow. Took about 30 minutes to do one file, while in the past it took about 5-6 minutes.   I am guessing is due to the lack of GPU? 

The work around using the .6i with the fallback runtime describe above runs great though.

**Comment by dgoryeo** [comment] 2024-01-04 21:37
Both 0.6 and beta 1.0 use GPU. The difference is in the quantisation (CTranslate2) method. The beta release is using the standard Whisper and standard silero VAD. The 0.6 uses fast whisper with quantised and batch processing of model and VAD.

**Comment by foristickman** [comment] 2024-01-05 05:01
It's working fine for me too even if it is slower. 

> The work around using the .6i with the fallback runtime describe above runs great though.

This will only be supported until the end of the month though so you'll have no choice but to use the current version.

**Comment by meizhong986** [comment] 2024-01-05 11:08
Version 0.7 was just released. This release has the fix for the break after the colab upgrade. No need for the fallback runtime in this release.

**Comment by foristickman** [comment] 2024-01-05 11:17
Thanks for the work. 

btw I noticed a spelling mistake in the notes at the bottom:

0.7: fixing the error caused bu Colab upgrade

should be by not bu

**Comment by meizhong986** [comment] 2024-01-06 00:25
The fix is in version 0.7.
Please check that one out --should work fine.

**Closed** 2024-12-21 23:22 UTC
